version: '3.4'
services:
  postgres:
    image: postgres:12.1
    container_name: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 6444:5432
  weather:
    container_name: weather
    command: migrate
    depends_on:
      - postgres
    build:
      context: ./migrations
      dockerfile: ./Dockerfile
